CREATE TABLE [dbo].[Table]
(
	[D_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [DISASTER_NAME] VARCHAR(50) NULL, 
    [START_DATE] DATE NULL, 
    [END_DATE] DATE NULL, 
    [LOCATION] VARCHAR(50) NULL, 
    [DESCRIPTION] VARCHAR(50) NULL
)
